import 'package:flutter/material.dart';

import '../shadow_store/shadow_store.dart';

/// A compact button with a customizable background color and shadow.
///
/// The shadow is generated by [ShadowStore.shadowV3] using [shadowColor].
///
/// Example:
/// `dart
/// ShadowButton(
///   shadowColor: Colors.blue,
///   onPressed: () {},
///   child: const Text('Save'),
/// )
/// `
class ShadowButton extends StatelessWidget {
  /// Creates a shadow-styled button.
  const ShadowButton({
    super.key,
    required this.child,
    required this.shadowColor,
    required this.onPressed,
  });

  /// The content displayed inside the button.
  final Widget child;

  /// Background color and source color used to generate the shadow.
  final Color shadowColor;

  /// Called when the button is pressed.
  final VoidCallback onPressed;

  static const double _width = 100;
  static const double _height = 28;
  static const double _radius = 4;
  static const double _borderWidth = 2;

  @override
  Widget build(BuildContext context) {
    final borderRadius = BorderRadius.circular(_radius);

    return SizedBox(
      width: _width,
      height: _height,
      child: Material(
        color: shadowColor,
        borderRadius: borderRadius,
        child: InkWell(
          onTap: onPressed,
          borderRadius: borderRadius,
          child: DecoratedBox(
            decoration: BoxDecoration(
              borderRadius: borderRadius,
              boxShadow: ShadowStore.shadowV3(shadowColor),
              border: Border.all(
                color: Colors.transparent,
                width: _borderWidth,
              ),
            ),
            child: Center(child: child),
          ),
        ),
      ),
    );
  }
}
